name: "Export-Solution"
#description: "Exports solution"
#author: "Joseph-Duty-VA"

on:
  workflow_dispatch: 
    inputs:
      source-org: 
        description: "source of solution"
        required: true
        default: 'https://dvagov-veft-dev.crm9.dynamics.com'
      solution-name:
        description: "schema name of solution"
        required: true
        default: "deploy_solution"

jobs:
  export-solution:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        lfs: true

    # - name: who-am-i action
    #   uses: microsoft/powerplatform-actions/who-am-i@latest
    #   with:
    #     environment-url: ${{ github.event.inputs.source-org }}" 
    #     app-id: ${{ secrets.crm_dev_clientid }}
    #     client-secret: ${{ secrets.crm_dev_clientid }}
    #     tenant-id: "e95f1b23-abaf-45ee-821d-b7ab251ab3bf"
    #     # user-name: ${{ secrets.crm_dev_clientid }}
    #     # password-secret: ${{ secrets.crm_dev_clientsecret }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{ github.event.inputs.source-org }}"
        app-id: ${{ secrets.crm_dev_clientid }}
        client-secret: ${{ secrets.crm_dev_clientid }}
        tenant-id: "e95f1b23-abaf-45ee-821d-b7ab251ab3bf"
        solution-name: ${{ github.event.inputs.solution-name }}" 
        solution-output-file: '${{ github.event.inputs.solution-name }}.zip'
        working-directory: 'out'

    # - name: unpack-solution action
    #   uses: microsoft/powerplatform-actions/unpack-solution@v0
    #   with:
    #     solution-file: 'out/exported/${{ github.event.inputs.solution-name }}.zip'
    #     solution-folder: out/solutions/${{ github.event.inputs.solution-name }}
    #     solution-type: 'Unmanaged'
    #     overwrite-files: true

    # - name: branch-solution, prepare it for a PullRequest
    #   uses: microsoft/powerplatform-actions/branch-solution@v0
    #   with:
    #     solution-folder: out/solutions/${{ github.event.inputs.solution-name }}
    #     solution-target-folder: solutions/${{ github.event.inputs.solution-name }}
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     allow-empty-commit: true
