# This workflow is run only manually, as it uses a workflow_dispatch. It is recommended to use cron or push into main branch to trigger this. Since this workflow also commits into the repo, use ignore tags to prevent infinite loop. Refer https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-branches-and-tags

name: extract-and-deploy
on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: "Solution Name"
        required: true
        default: "CICDRelease"
      sourceEnvironmentUrl:
        description: "Source Environment URL"
        required: true
        default: "https://dvagov-veft-dev.crm9.dynamics.com"
      targetEnvironmentUrl:
        description: "Target Environment URL"
        required: true
        default: "https://dvagov-veft-int.crm9.dynamics.com"
      release:
        description: "Release?"
        required: true
        default: true
      managed:
        description: "Managed?"
        required: true
        default: true
      debug:
        description: "Debug?"
        required: true
        default: "true"

jobs:
  build:
    # The type of runner that the job will run on. This needs to be Windows runner.
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        if: github.event.inputs.debug == 'true'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Extract Solution
        id: extract-solution
        uses: rajyraman/powerapps-solution-extract@v1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          solutionName: ${{ github.event.inputs.solutionName }}
          sourceEnvironmentUrl: ${{ github.event.inputs.sourceEnvironmentUrl }}
          applicationId: ${{ secrets.CRM_DEV_CLIENTID }}
          applicationSecret: ${{ secrets.CRM_DEV_CLIENTSECRET }}
          releaseSolution: ${{ github.event.inputs.release }}

      - name: Deploy Solution
        id: deploy-solution
        uses: rajyraman/powerapps-deploy-solution@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          solutionName: ${{ github.event.inputs.solutionName }}
          targetEnvironmentUrl: ${{ github.event.inputs.targetEnvironmentUrl }}
          applicationId: ${{ secrets.CRM_DEV_CLIENTID }}
          applicationSecret: ${{ secrets.CRM_DEV_CLIENTSECRET }}
          tag: ${{ steps.extract-solution.outputs.solutionVersion }}
          managed: ${{ github.event.inputs.managed }}
